### ISSUE TITLE
Make preview display justified text

### ISSUE THREAD

**Issue by ewilazarus** [neilsustc/vscode-markdown#202]
The preview window always display text aligned to the left side of the screen. It would be good if there was a setting to make it possible to choose between wither "justified" or "none".

Write a paragraph and open the preview window.

There are no messages

**Comment by neilsustc** [comment]
You can do it with a few CSS styles

1. create a CSS file named `centered.css`

```css
body {
    max-width: 768px; /* or another width you like */
    margin: auto;
}
```

2. set it in your settings

```json
"markdown.styles": [
    "/path/to/centered.css"
]
```
