### ISSUE TITLE
Table of contents occur err！

### ISSUE THREAD

**Issue by zcc0721** [neilsustc/vscode-markdown#347]
hi！

My markdown file is:

```
---
html:
  embed_local_images: false
  embed_svg: true
  offline: true
  toc: true

print_background: false

export_on_save:
  html: true
---

## One

some contents.

## Two

some contents.

## Three

some contents.
```

Then, I created a toc using SHIFT+COMMAND+P, then select `create table of contents` like this:
![image](https://user-images.githubusercontent.com/17916496/50421586-10109580-087c-11e9-9563-cdc77e8546ed.png)

then, my markdown file is:

```
---
html:
  embed_local_images: false
  embed_svg: true
  offline: true
  toc: true

print_background: false

export_on_save:
  html: true
---

- [html: true](#html-true)
- [One](#one)
- [Two](#two)
- [Three](#three)

## One

some contents.

## Two

some contents.

## Three

some contents.
```

Do you see that? The title One, Two, Three is correct, but the first item of toc is not correct. Like this:

![image](https://user-images.githubusercontent.com/17916496/50421651-c7a5a780-087c-11e9-99dd-881cf8a7528b.png)

My env is：

- vscode is v1.30.1
- macOS Mojava 10.14.2
- my `Markdown All in One` is 1.8.0

Thank you.
